name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t my-app:latest .

      - name: Run tests
        run: echo "Tests would run here"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy Application
        run: echo "Deploy step would go here"
